[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
upload_speed = 115200  # Adjust the upload speed if necessary
monitor_speed = 115200  # Serial monitor speed
lib_deps =
    bblanchon/ArduinoJson @ ^7.2.0
    esphome/AsyncTCP-esphome @ ^2.1.4
    esphome/ESPAsyncWebServer-esphome @ ^3.2.2
    tzapu/WiFiManager @ ^2.0.17
    adafruit/Adafruit SSD1306@^2.5.11
    adafruit/Adafruit GFX Library @ ^1.11.10
    FS
    Update
    WebServer
    DNSServer
    h2zero/NimBLE-Arduino @ ^1.4.2