[env:esp32c3]
platform = espressif32@6.6.0
board = esp32-c3-devkitm-1
framework = arduino

lib_deps =
    ;adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    ;adafruit/Adafruit GFX Library @ 1.11.11
    ;adafruit/Adafruit BusIO @ ^1.16.1
    ;Wire
    ;FS
    ;SPI
    bodmer/TFT_eSPI @ ^2.5.43
    ;moononournation/GFX Library for Arduino @ 1.5.0
    bitbank2/AnimatedGIF @ ^2.1.1